# Generated by Django 3.1.3 on 2020-11-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend', models.DecimalField(decimal_places=2, default='', max_digits=10, null=True)),
                ('applicant', models.DecimalField(decimal_places=2, default='', max_digits=10, null=True)),
            ],
            options={
                'db_table': 'moneys',
            },
        ),
        migrations.AddField(
            model_name='salary',
            name='salary',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, null=True),
        ),
    ]
