# Generated by Django 3.1.3 on 2020-11-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201118_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='carrer',
        ),
        migrations.DeleteModel(
            name='Carrer',
        ),
    ]
