# Generated by Django 3.1.3 on 2020-11-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20201118_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tag_companies',
            field=models.ManyToManyField(through='company.Tag_company', to='company.Sub_tag'),
        ),
    ]
