# Generated by Django 3.1.3 on 2020-11-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_tag_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrer', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'carrers',
            },
        ),
    ]
