# Generated by Django 3.1.3 on 2020-11-18 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_district_district_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sub_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tags', to='company.sub_tag'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tag_companies',
            field=models.ManyToManyField(null=True, related_name='tag_companies', through='company.Tag_company', to='company.Sub_tag'),
        ),
    ]
