# Generated by Django 3.1.3 on 2020-11-18 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20201118_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='district_categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.district_category'),
        ),
    ]
