# Generated by Django 3.1.3 on 2020-11-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_district_district_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='district_categories',
        ),
    ]
