# Generated by Django 3.1.3 on 2020-11-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_district_district_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='tag_companies',
        ),
    ]
