# Generated by Django 3.1.3 on 2020-11-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_remove_company_tag_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='sub_tag',
        ),
        migrations.AddField(
            model_name='company',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.district'),
        ),
        migrations.AddField(
            model_name='company',
            name='money',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.money'),
        ),
        migrations.AddField(
            model_name='company',
            name='subcategories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.subcategory'),
        ),
    ]
