# Generated by Django 3.1.3 on 2020-11-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20201118_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tag_companies',
            field=models.ManyToManyField(related_name='tag_companies', through='company.Tag_company', to='company.Sub_tag'),
        ),
    ]
