# Generated by Django 3.1.3 on 2020-11-18 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_district_district_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='carrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.carrer'),
        ),
    ]
