# Generated by Django 3.1.3 on 2020-11-18 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(max_length=45)),
                ('year', models.CharField(max_length=45)),
                ('detail', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('detail', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'awards',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=45)),
                ('school_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Past_carrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=45)),
                ('company', models.CharField(max_length=45)),
                ('achevement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.achievement')),
            ],
            options={
                'db_table': 'past_carrers',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=200)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.award')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.grade')),
                ('past_carrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.past_carrer')),
            ],
            options={
                'db_table': 'resumes',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contens', models.CharField(max_length=1000)),
                ('from_commender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomender_from_comender', to='user.user')),
                ('to_comender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomender_to_comender', to='user.user')),
            ],
            options={
                'db_table': 'recommenders',
            },
        ),
    ]
