# Generated by Django 3.1.3 on 2020-11-18 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_carrer'),
        ('user', '0005_auto_20201118_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_carrer_filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.carrer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'user_district_filters',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='carrer_filter',
            field=models.ManyToManyField(related_name='user_careers_filters', through='user.User_carrer_filter', to='company.Carrer'),
        ),
    ]
