# Generated by Django 3.1.3 on 2020-11-18 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_resumes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resumes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.resume'),
        ),
    ]
