# Generated by Django 3.1.3 on 2020-11-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201118_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recomender',
            field=models.ManyToManyField(related_name='recomenders', through='user.Recommendation', to='user.User'),
        ),
    ]
